files:
  include: 'styles/**/*.s+(a|c)ss'
options:
  formatter: stylish
  merge-default-rules: false
rules:
  bem-depth:
    - 1
    - max-depth: 1
  border-zero: 1
  brace-style:
    - 1
    - allow-single-line: true
  class-name-format:
    - 0
    - convention: BEM
  clean-import-paths:
    - 1
    - filename-extension: false
      leading-underscore: false
  empty-line-between-blocks:
    - 1
    - allow-single-line-rulesets: false
  extends-before-declarations: 1
  extends-before-mixins: 1
  final-newline:
    - 1
    - include: true
  force-attribute-nesting: 1
  force-element-nesting: 1
  force-pseudo-nesting: 1
  function-name-format:
    - 0
    - convention: BEM
  hex-length: 0
  hex-notation:
    - 1
    - style: lowercase
  id-name-format:
    - 0
    - convention: BEM
  indentation:
    - 1
    - size: 2
  leading-zero:
    - 1
    - include: false
  mixin-name-format:
    - 0
    - convention: BEM
  mixins-before-declarations: 0
  nesting-depth:
    - 1
    - max-depth: 4
  no-color-keywords: 0
  no-color-literals: 0
  no-css-comments: 0
  no-debug: 1
  no-duplicate-properties: 1
  no-empty-rulesets: 1
  no-important: 0
  no-invalid-hex: 1
  no-mergeable-selectors: 1
  no-misspelled-properties:
    - 1
    - extra-properties: []
  no-qualifying-elements: 1
  no-trailing-zero: 1
  no-url-protocols: 1
  placeholder-in-extend: 1
  placeholder-name-format:
    - 0
    - convention: BEM
  property-sort-order:
    - 1
    - ignore-custom-properties: false
  quotes:
    - 1
    - style: single
  shorthand-values: 1
  single-line-per-selector: 1
  space-after-bang:
    - 1
    - include: false
  space-after-colon:
    - 1
    - include: true
  space-after-comma: 1
  space-before-bang:
    - 1
    - include: true
  space-before-brace:
    - 1
    - include: true
  space-before-colon: 1
  space-between-parens:
    - 1
    - include: false
  trailing-semicolon: 1
  url-quotes: 1
  variable-name-format:
    - 0
    - convention: BEM
  zero-unit: 1
